---

- name: Install php-fpm 7.2
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
    update_cache: true
  vars:
    packages:
    - php-fpm
    - php-mysql

- name: Enable php-fpm
  service: 
    name: php7.2-fpm
    enabled: yes
    state: started
